name: co_po_generator
description: "A CO-PO Attainment Generator for FET, Jain University"
publish_to: 'none'
version: 0.5.0-alpha

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.2
  image: ^4.1.7
  open_file: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/api/
    - assets/samples/
    - assets/samples/IA/1/
    - assets/samples/IA/2/

# msix packaging configuration
# run with the command [dart run msix:create] or [dart run msix:publish]
msix_config:
  display_name: CO-PO Generator
  publisher_display_name: Jery
  publisher: Jery
  identity_name: com.jery.co-po-generator
  output_path: windows\installer\
  build_windows: false
  windows_build_args: "--obfuscate --split-debug-info=./build/debug-info"
  app_installer:
    publish_folder_path: setup\
  logo_path: windows\runner\resources\app_icon.ico
  capabilities: internetClient
